arc_gis:
  max_page_size: 2000

cleanup_rules:
  replace:
    - field: "PlaceName"
      match: "AURORA CO"
      replacement: "AURORA"
    - field: "PlaceName"
      match: "STRASBURG CO"
      replacement: "STRASBURG"
    - field: "PlaceName"
      match: "BYERS, CO"
      replacement: "BYERS"
    - field: "PlaceName"
      match: "Watkins, CO"
      replacement: "WATKINS"
    - field: "PlaceName"
      match: "UNINC ADAM"
      replacement: "ADAMS COUNTY"
    - field: "PlaceName"
      match: "UNINC DOUG"
      replacement: "DOUGLAS COUNTY"
    - field: "PlaceName"
      match: "UNINC ELBE"
      replacement: "ELBERT COUNTY"
  exclude:
    - field: "PlaceName"
      match: "107"
    - field: "PlaceName"
      match: "113"
    - field: "PlaceName"
      match: "115"
    - field: "PlaceName"
      match: "123"
    - field: "PlaceName"
      match: "138"
    - field: "PlaceName"
      match: "143"

# To get list of zipcodes:
# 1. Go to: https://oms.core.coop
# 2. Open the outages side panel and show Zipcodes
# 3. Run JS: Array.from(document.querySelectorAll('.customer_outages .detail_row .title')).map(n => n.innerHTML)
zipcodes:
  - "80015"
  - "80016"
  - "80102"
  - "80103"
  - "80104"
  - "80105"
  - "80106"
  - "80107"
  - "80108"
  - "80109"
  - "80112"
  - "80116"
  - "80117"
  - "80118"
  - "80125"
  - "80127"
  - "80131"
  - "80132"
  - "80133"
  - "80134"
  - "80135"
  - "80136"
  - "80137"
  - "80138"
  - "80401"
  - "80421"
  - "80425"
  - "80432"
  - "80433"
  - "80439"
  - "80440"
  - "80448"
  - "80449"
  - "80452"
  - "80456"
  - "80465"
  - "80470"
  - "80475"
  - "80642"
  - "80643"
  - "80813"
  - "80814"
  - "80816"
  - "80819"
  - "80820"
  - "80827"
  - "80863"
  - "80921"
  - "81211"
  - "81212"
